"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeftIcon, ArrowUpRightIcon } from "@heroicons/react/24/outline";
import { useSitePreferences } from "@/context/SitePreferences";

const projects={
  "aci-benek-tespiti":{
    images:["/sirket.png"],links:[],
    tr:{no:"01",type:"Computer Vision · Ar-Ge",title:"Erken Dönem Acı Benek Tespiti",summary:"Elmalarda acı benek hastalığını görünür belirtiler oluşmadan önce belirlemeyi hedefleyen görüntü işleme projesi.",problem:"Erken evrede gözle ayırt edilmesi zor olan hastalık, ürün kalitesini ve depolama sürecini doğrudan etkiliyor.",approach:"Dört ay boyunca 1.800 elma örneğinden endüstriyel RGB görüntüler toplandı. Görüntü ön işleme adımlarının ardından Multiple Instance Learning yaklaşımı değerlendirildi.",result:"Sahadan veri toplama, veri kalitesi, ön işleme ve model geliştirme süreçlerini bir araya getiren uçtan uca bir Ar-Ge akışı oluşturuldu.",stack:["Python","Deep Learning","MIL","Image Processing"]},
    en:{no:"01",type:"Computer Vision · R&D",title:"Early Bitter Pit Detection",summary:"A computer-vision project aiming to identify bitter pit disease in apples before visible symptoms emerge.",problem:"The disease is difficult to distinguish at an early stage and directly affects product quality and storage outcomes.",approach:"Industrial RGB images were collected from 1,800 apple samples over four months. Multiple Instance Learning was evaluated after image preprocessing.",result:"An end-to-end R&D workflow combining field data collection, data quality, preprocessing and model development.",stack:["Python","Deep Learning","MIL","Image Processing"]}
  },
  "iot-siber-guvenlik":{
    images:["/11.jpeg","/21.jpeg","/31.jpeg"],links:[{label:"GitHub",url:"https://github.com/SedanurCeylan/tubitakprojesi"},{label:"IEEE",url:"https://ieeexplore.ieee.org/document/10778718"}],
    tr:{no:"02",type:"TÜBİTAK 2209-A · Siber Güvenlik",title:"IoT Siber Güvenlik Platformu",summary:"IoT sızma testi eğitimleri için özgün zararlı yazılım veri setleri üreten üretici yapay zekâ destekli platform.",problem:"Gerçekçi saldırı verisine erişim; güvenlik, gizlilik ve veri çeşitliliği nedeniyle eğitim ortamlarında sınırlı kalıyor.",approach:"GAN mimarisine sahip iki sinir ağıyla sentetik saldırı verisi üretildi ve sonuçlar web arayüzü üzerinden erişilebilir hale getirildi.",result:"Çalışma TÜBİTAK 2209-A kapsamında desteklendi ve proje çıktısından hazırlanan makale IEEE Xplore'da yayımlandı.",stack:["GAN","IoT Security","Python","ASP.NET"]},
    en:{no:"02",type:"TÜBİTAK 2209-A · Cybersecurity",title:"IoT Cybersecurity Platform",summary:"A generative-AI platform producing original malware datasets for IoT penetration-testing education.",problem:"Access to realistic attack data is limited in learning environments due to security, privacy and data-diversity constraints.",approach:"Synthetic attack data was generated through two neural networks in a GAN architecture and delivered through a web interface.",result:"The project was supported by TÜBİTAK 2209-A and its resulting paper was published in IEEE Xplore.",stack:["GAN","IoT Security","Python","ASP.NET"]}
  },
  "kripto-paneli":{
    images:["/1.jpeg","/2.jpeg","/4.jpeg","/5.jpeg","/6.jpeg"],links:[{label:"GitHub",url:"https://github.com/SedanurCeylan/TurkcellFinal"},{label:"Live",url:"https://cryptoproject-ten.vercel.app/en"}],
    tr:{no:"03",type:"Full-stack Web Ürünü",title:"Kripto Al-Sat Paneli",summary:"Piyasa takibi, favoriler ve cüzdan yönetimini tek deneyimde birleştiren çok dilli kripto platformu.",problem:"Kullanıcıların piyasa verisini takip ederken portföy ve favori işlemlerini farklı araçlarda yönetmesi gerekiyor.",approach:"CoinMarketCap verileri Next.js arayüzünde işlendi; Firebase ile kullanıcı, favori ve cüzdan akışları oluşturuldu.",result:"Gerçek zamanlı veri, kimlik yönetimi ve responsive arayüzü bir araya getiren çalışan bir web ürünü geliştirildi.",stack:["Next.js","Firebase","REST API","i18n"]},
    en:{no:"03",type:"Full-stack Web Product",title:"Crypto Trading Dashboard",summary:"A multilingual crypto platform combining market tracking, favorites and wallet management.",problem:"Users often manage market data, portfolios and favorites across separate tools.",approach:"CoinMarketCap data was processed in a Next.js interface, with Firebase handling user, favorites and wallet flows.",result:"A working web product combining real-time data, identity management and a responsive interface.",stack:["Next.js","Firebase","REST API","i18n"]}
  },
  "eticaret-sistemi":{
    images:["/yakında.jpg"],links:[{label:"GitHub",url:"https://github.com/SedanurCeylan/eticaret-v1"},{label:"Demo",url:"https://youtu.be/MT3d4ME_MZc"}],
    tr:{no:"04",type:"Backend · Web Sistemleri",title:"E-Ticaret Yönetim Sistemi",summary:"Ürün, sepet, sipariş ve yönetim süreçlerini kapsayan katmanlı e-ticaret uygulaması.",problem:"Temel satış akışlarının güvenli kullanıcı yönetimi ve sürdürülebilir veri modeliyle birlikte ele alınması gerekiyor.",approach:"ASP.NET 9 ve Entity Framework Core ile Code-First veri yapısı kuruldu; Identity ile rol ve kullanıcı yönetimi eklendi.",result:"Müşteri ve yönetici akışlarını aynı sistemde buluşturan, geliştirilmeye açık modüler bir temel hazırlandı.",stack:["ASP.NET 9","EF Core","SQLite","Identity"]},
    en:{no:"04",type:"Backend · Web Systems",title:"E-commerce Management System",summary:"A layered e-commerce application covering product, cart, order and administration workflows.",problem:"Core sales flows need to work alongside secure user management and a maintainable data model.",approach:"A Code-First data structure was built with ASP.NET 9 and Entity Framework Core, with Identity supporting roles and users.",result:"A modular foundation connecting customer and administrator workflows within one system.",stack:["ASP.NET 9","EF Core","SQLite","Identity"]}
  }
};

const ui={tr:{back:"Projelere dön",problem:"Problem",approach:"Yaklaşım",result:"Çıktı",tech:"Teknolojiler",links:"Bağlantılar"},en:{back:"Back to projects",problem:"Problem",approach:"Approach",result:"Outcome",tech:"Technology",links:"Links"}};

export default function ProjectDetail({slug}){const{language}=useSitePreferences();const project=projects[slug];if(!project)return null;const p=project[language];const t=ui[language];return <main className="project-detail"><div className="section-wrap"><Link href="/#projeler" className="detail-back"><ArrowLeftIcon/>{t.back}</Link><header className="detail-hero"><div><p>{p.no} / {p.type}</p><h1>{p.title}</h1><span>{p.summary}</span></div><div className="detail-cover"><Image src={project.images[0]} alt={p.title} fill priority className="object-cover" sizes="(max-width: 800px) 100vw, 48vw"/></div></header><section className="detail-body"><aside><p>{t.tech}</p><div>{p.stack.map(item=><span key={item}>{item}</span>)}</div>{project.links.length>0&&<><p>{t.links}</p><div className="detail-links">{project.links.map(link=><a key={link.url} href={link.url} target="_blank" rel="noreferrer">{link.label}<ArrowUpRightIcon/></a>)}</div></>}</aside><div className="detail-story"><article><span>01</span><div><h2>{t.problem}</h2><p>{p.problem}</p></div></article><article><span>02</span><div><h2>{t.approach}</h2><p>{p.approach}</p></div></article><article><span>03</span><div><h2>{t.result}</h2><p>{p.result}</p></div></article></div></section>{project.images.length>1&&<section className="detail-gallery">{project.images.slice(1).map((image,index)=><div key={image}><Image src={image} alt={`${p.title} ${index+2}`} fill className="object-cover" sizes="(max-width: 720px) 100vw, 50vw"/></div>)}</section>}</div></main>}
