"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { useSiteContent } from "@/context/SiteContent";

export default function AdminPage() {
  const { content, ready, saveContent, resetContent } = useSiteContent();
  const [draft, setDraft] = useState(content);
  const [language, setLanguage] = useState("tr");
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const [cvStatus, setCvStatus] = useState("");
  const [imageStatus, setImageStatus] = useState("");

  useEffect(() => { if (ready) setDraft(content); }, [content, ready]);
  if (!ready) return <main className="admin-page"><p>Panel yükleniyor…</p></main>;

  const updateHero = (field, value) => setDraft((current) => ({ ...current, [language]: { ...current[language], hero: { ...current[language].hero, [field]: value } } }));
  const updateSection = (section, field, value) => setDraft((current) => ({ ...current, [language]: { ...current[language], [section]: { ...current[language][section], [field]: value } } }));
  const updateItem = (section, index, field, value) => setDraft((current) => ({ ...current, [language]: { ...current[language], [section]: { ...current[language][section], items: current[language][section].items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: ["tags", "skills"].includes(field) ? value.split(",").map((part) => part.trim()).filter(Boolean) : value } : item) } } }));
  const updateSkills = (field, value) => setDraft((current) => ({ ...current, [language]: { ...current[language], skills: { ...current[language].skills, [field]: value } } }));
  const updateCategory = (index, field, value) => setDraft((current) => {
    const categories = current[language].skills.categories.map((category, categoryIndex) => categoryIndex === index ? { ...category, [field]: field === "skills" ? value.split(",").map((item) => item.trim()).filter(Boolean) : value } : category);
    return { ...current, [language]: { ...current[language], skills: { ...current[language].skills, categories } } };
  });
  const updateProject = (index, field, value) => setDraft((current) => {
    const projects = current[language].projects.map((project, projectIndex) => projectIndex === index ? { ...project, [field]: field === "technologies" ? value.split(",").map((item) => item.trim()).filter(Boolean) : value } : project);
    return { ...current, [language]: { ...current[language], projects } };
  });
  const addProject = () => setDraft((current) => {
    const projects = [...current[language].projects, { no: String(current[language].projects.length + 1).padStart(2, "0"), slug: `yeni-proje-${Date.now()}`, title: "Yeni Proje", type: "Proje", image: "/yakında.jpg", meta: "", technologies: [], text: "", externalUrl: "", github: "", visible: true, featured: false }];
    return { ...current, [language]: { ...current[language], projects } };
  });
  const removeProject = (index) => { if (!window.confirm("Bu proje kaldırılsın mı?")) return; setDraft((current) => ({ ...current, [language]: { ...current[language], projects: current[language].projects.filter((_, projectIndex) => projectIndex !== index) } })); };
  const uploadCv = async (event) => { const file = event.target.files?.[0]; if (!file) return; setCvStatus("Yükleniyor…"); setError(""); const body = new FormData(); body.append("cv", file); const response = await fetch("/api/cv", { method: "POST", body }); const data = await response.json(); if (!response.ok) { setError(data.error); setCvStatus(""); return; } setCvStatus("CV güncellendi"); };
  const uploadImage = async (file, onComplete) => { if (!file) return; setError(""); setImageStatus("Fotoğraf yükleniyor…"); const body = new FormData(); body.append("image", file); const response = await fetch("/api/media", { method: "POST", body }); const data = await response.json(); if (!response.ok) { setImageStatus(""); return setError(data.error); } onComplete(data.path); setImageStatus("Fotoğraf yüklendi · Kaydet butonuna bas"); };
  const handleSave = async (event) => { event.preventDefault(); setError(""); try { await saveContent(draft); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } catch (saveError) { setError(saveError.message); } };
  const handleReset = async () => { if (!window.confirm("Tüm düzenlemeler varsayılan içeriğe döndürülsün mü?")) return; try { await resetContent(); } catch (resetError) { setError(resetError.message); } };
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/admin/giris"; };
  const t = draft[language];

  return <main className="admin-page"><div className="admin-shell">
    <div className="admin-window-bar"><div><i/><i/><i/></div><span>Portfolyo Yönetimi — Sedanur Ceylan</span><small>⚙️</small></div><header className="admin-header"><div><p>PORTFOLYO YÖNETİMİ</p><h1>İçerik paneli</h1></div><div className="admin-header-actions"><Link href="/"><span>⌂</span> Siteye dön</Link><button type="button" onClick={logout}><span>↪</span> Çıkış</button></div></header>
    <div className="admin-notice">Değişiklikler Firebase Firestore veritabanına kaydedilir ve yayınlanan sitedeki tüm ziyaretçilere yansır.</div>
    <div className="admin-language" role="group" aria-label="Düzenleme dili"><button type="button" className={language === "tr" ? "active" : ""} onClick={() => setLanguage("tr")}>Türkçe</button><button type="button" className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")}>English</button></div>
    <form onSubmit={handleSave} className="admin-form">
      <section className="admin-card"><div className="admin-card-title"><span>01</span><div><h2>Hero</h2><p>Ana sayfanın ilk ekranındaki içerikler.</p></div></div><div className="admin-fields">
        <label>Ad<input value={t.hero.firstName} onChange={(event) => updateHero("firstName", event.target.value)} /></label><label>Soyad<input value={t.hero.lastName} onChange={(event) => updateHero("lastName", event.target.value)} /></label><label>Meslek<input value={t.hero.role} onChange={(event) => updateHero("role", event.target.value)} /></label><label>Uzmanlık satırı<input value={t.hero.fields} onChange={(event) => updateHero("fields", event.target.value)} /></label>
      </div></section>
      <section className="admin-card"><div className="admin-card-title"><span>02</span><div><h2>Beceriler</h2><p>Başlıkları ve virgülle ayrılmış teknolojileri düzenle.</p></div></div><div className="admin-fields"><label>Bölüm başlığı<input value={t.skills.label} onChange={(event) => updateSkills("label", event.target.value)} /></label><label>Alt metin<input value={t.skills.subtitle} onChange={(event) => updateSkills("subtitle", event.target.value)} /></label></div><div className="admin-category-grid">{t.skills.categories.map((category, index) => <fieldset key={category.key}><legend>Kategori {index + 1}</legend><label>Başlık<input value={category.title} onChange={(event) => updateCategory(index, "title", event.target.value)} /></label><label>Teknolojiler<textarea rows="3" value={category.skills.join(", ")} onChange={(event) => updateCategory(index, "skills", event.target.value)} /></label></fieldset>)}</div></section>
      <section className="admin-card"><div className="admin-card-title"><span>03</span><div><h2>Hakkımda</h2><p>Profil fotoğrafı ve tanıtım içeriği.</p></div></div><div className="admin-about-layout"><div className="admin-photo-editor"><div className="admin-photo-preview"><Image src={t.about.image} alt="Mevcut hakkımda fotoğrafı" fill className="object-cover" sizes="180px" unoptimized={t.about.image.startsWith("/api/")}/></div><label className="admin-photo-button">Fotoğrafı değiştir<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>uploadImage(e.target.files?.[0],path=>updateSection("about","image",path))}/></label><small>{imageStatus || "JPG, PNG veya WebP · en fazla 8 MB"}</small></div><div className="admin-fields"><label>Başlık<input value={t.about.title} onChange={(e)=>updateSection("about","title",e.target.value)}/></label><label>Konum<input value={t.about.location} onChange={(e)=>updateSection("about","location",e.target.value)}/></label><label>Birinci paragraf<textarea rows="3" value={t.about.body} onChange={(e)=>updateSection("about","body",e.target.value)}/></label><label>İkinci paragraf<textarea rows="3" value={t.about.body2} onChange={(e)=>updateSection("about","body2",e.target.value)}/></label><label>Etiketler<input value={t.about.skills.join(", ")} onChange={(e)=>updateSection("about","skills",e.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/></label></div></div></section>
      <section className="admin-card"><div className="admin-card-title"><span>04</span><div><h2>Projeler</h2><p>Anasayfadaki projeler bölümünü buradan düzenle.</p></div><button type="button" className="admin-add" onClick={addProject}>+ Proje ekle</button></div><div className="admin-project-list">{t.projects.map((project, index) => <fieldset key={`${project.slug}-${index}`} className="admin-project"><legend>{project.no} · {project.title}</legend><div className="admin-fields"><label>Proje adı<input value={project.title} onChange={(event) => updateProject(index, "title", event.target.value)} /></label><label>Kategori<input value={project.type} onChange={(event) => updateProject(index, "type", event.target.value)} /></label><label>Açıklama<textarea rows="2" value={project.text} onChange={(event) => updateProject(index, "text", event.target.value)} /></label><label>Teknolojiler<input value={(project.technologies || []).join(", ")} onChange={(event) => updateProject(index, "technologies", event.target.value)} /></label><label>Proje görseli<input type="file" accept="image/*" onChange={(e)=>uploadImage(e.target.files?.[0],path=>updateProject(index,"image",path))}/></label><label>Harici bağlantı<input value={project.externalUrl || ""} onChange={(event) => updateProject(index, "externalUrl", event.target.value)} placeholder="https://..." /></label><label>GitHub<input value={project.github || ""} onChange={(event) => updateProject(index, "github", event.target.value)} /></label><label>Meta bilgi<input value={project.meta || ""} onChange={(event) => updateProject(index, "meta", event.target.value)} /></label></div><div className="admin-project-actions"><label className="admin-check"><input type="checkbox" checked={project.visible !== false} onChange={(event) => updateProject(index, "visible", event.target.checked)} /> Sitede göster</label><button type="button" onClick={() => removeProject(index)}>Projeyi kaldır</button></div></fieldset>)}</div></section>
      <section className="admin-card"><div className="admin-card-title"><span>05</span><div><h2>Deneyim</h2><p>Çalışma geçmişindeki bütün alanlar.</p></div></div><div className="admin-fields"><label>Bölüm başlığı<input value={t.experience.title} onChange={(e)=>updateSection("experience","title",e.target.value)}/></label></div><div className="admin-project-list">{t.experience.items.map((item,index)=><fieldset key={index} className="admin-project"><legend>{item.company}</legend><div className="admin-fields"><label>Tarih<input value={item.period} onChange={(e)=>updateItem("experience",index,"period",e.target.value)}/></label><label>Şirket<input value={item.company} onChange={(e)=>updateItem("experience",index,"company",e.target.value)}/></label><label>Pozisyon<input value={item.role} onChange={(e)=>updateItem("experience",index,"role",e.target.value)}/></label><label>Açıklama<textarea value={item.text} onChange={(e)=>updateItem("experience",index,"text",e.target.value)}/></label><label>Etiketler<input value={item.tags.join(", ")} onChange={(e)=>updateItem("experience",index,"tags",e.target.value)}/></label></div></fieldset>)}</div></section>
      <section className="admin-card"><div className="admin-card-title"><span>06</span><div><h2>Eğitim</h2></div></div><div className="admin-fields"><label>Bölüm başlığı<input value={t.education.title} onChange={(e)=>updateSection("education","title",e.target.value)}/></label></div><div className="admin-project-list">{t.education.items.map((item,index)=><fieldset key={index} className="admin-project"><legend>{item.school}</legend><div className="admin-fields"><label>Tarih<input value={item.period} onChange={(e)=>updateItem("education",index,"period",e.target.value)}/></label><label>Program<input value={item.degree} onChange={(e)=>updateItem("education",index,"degree",e.target.value)}/></label><label>Tür<input value={item.type} onChange={(e)=>updateItem("education",index,"type",e.target.value)}/></label><label>Okul<input value={item.school} onChange={(e)=>updateItem("education",index,"school",e.target.value)}/></label></div></fieldset>)}</div></section>
      <section className="admin-card"><div className="admin-card-title"><span>07</span><div><h2>Footer ve bağlantılar</h2></div></div><div className="admin-fields"><label>Birinci satır<input value={t.footer.line1} onChange={(e)=>updateSection("footer","line1",e.target.value)}/></label><label>İkinci satır<input value={t.footer.line2} onChange={(e)=>updateSection("footer","line2",e.target.value)}/></label><label>E-posta<input value={t.footer.email} onChange={(e)=>updateSection("footer","email",e.target.value)}/></label><label>GitHub<input value={t.footer.github} onChange={(e)=>updateSection("footer","github",e.target.value)}/></label><label>Instagram<input value={t.footer.instagram || ""} onChange={(e)=>updateSection("footer","instagram",e.target.value)} placeholder="https://instagram.com/..."/></label><label>LinkedIn<input value={t.footer.linkedin} onChange={(e)=>updateSection("footer","linkedin",e.target.value)}/></label></div></section>
      <section className="admin-card"><div className="admin-card-title"><span>08</span><div><h2>CV</h2><p>Yeni PDF yüklediğinde sitedeki CV butonu otomatik güncellenir.</p></div></div><label className="admin-upload">PDF dosyası seç<input type="file" accept="application/pdf" onChange={uploadCv} /><span>{cvStatus || "En fazla 8 MB · PDF"}</span></label></section>
      {error && <div className="admin-error" role="alert">{error}</div>}<div className="admin-actions"><button type="button" className="admin-reset" onClick={handleReset}><span>↻</span> Varsayılana dön</button><button type="submit" className="admin-save">{saved ? <><span>✓</span> Kaydedildi</> : "Değişiklikleri kaydet"}</button></div>
    </form>
  </div></main>;
}
